---
---
---

Build RcppML functions

```{r}
library(RcppML)
library(microbenchmark)


options(RcppML.threads = 8)
options(RcppML.verbose = TRUE)

data("aml")
A_dense <- aml$data

data("hawaiibirds")
A_sparse <- hawaiibirds$counts
```

Now generate and compare approximations based on IRLBA and RcppML

```{r}
m_rcppml <- svd_rcppml(A_dense, 10, tol = 1e-5, maxit = 1000)
A_rcppml <- (m_rcppml$u %*% diag(m_rcppml$d)) %*% t(m_rcppml$v)

m_irlba <- irlba::irlba(A_dense, 10, tol = 1e-5, maxit = 1000)
A_irlba <- (m_irlba$u %*% diag(m_irlba$d)) %*% t(m_irlba$v)

diff <- norm((A_irlba - A_rcppml), "F")
print("")
print("% difference between irlba and RcppML reconstructions")
print(diff / norm(A_irlba, "F"))

plot(1:100, A_irlba[1:100,1], type='l', col='green')
lines(1:100, A_rcppml[1:100,1], col='red')

plot(m_irlba$d, m_rcppml$d, type='l', col='green')
```

```{r}
m_rcppml <- svd_rcppml(A_sparse, 10, tol = 1e-5, maxit = 1000)
A_rcppml <- (m_rcppml$u %*% diag(m_rcppml$d)) %*% t(m_rcppml$v)

m_irlba <- irlba::irlba(A_sparse, 10, tol = 1e-5, maxit = 1000)
A_irlba <- (m_irlba$u %*% diag(m_irlba$d)) %*% t(m_irlba$v)

diff <- norm((A_irlba - A_rcppml), "F")
print("")
print("% difference between irlba and RcppML reconstructions")
print(diff / norm(A_irlba, "F"))

plot(1:100, A_irlba[1:100,1], type='l', col='green')
lines(1:100, A_rcppml[1:100,1], col='red')

plot(m_irlba$d, m_rcppml$d, type='l', col='green')
```

Benchmark time performance on dense data

```{r}
options(RcppML.verbose = FALSE)

mbm <- microbenchmark(
  "RcppML Rank 10" = {
    model <- svd_rcppml(A_dense, 10, tol = 1e-5, maxit = 1000)
  },
  "irlba Rank 10" = {
    model <- irlba::irlba(A_dense, 10, tol = 1e-5, maxit = 1000)
  }
  # 
  # "RcppML Rank 50" = {
  #   model <- svd_rcppml(A_dense, 50, tol = 1e-5, maxit = 1000)
  # },
  # "irlba Rank 50" = {
  #   model <- irlba::irlba(A_dense, 50, tol = 1e-5, maxit = 1000)
  # },
  # 
  # "RcppML Rank 100" = {
  #   model <- svd_rcppml(A_dense, 100, tol = 1e-5, maxit = 1000)
  # },
  # "irlba Rank 100" = {
  #   model <- irlba::irlba(A_dense, 100, tol = 1e-5, maxit = 1000)
  # }
)
mbm
```

Benchmark time performance on sparse data

```{r}
mbm <- microbenchmark(
  "RcppML Rank 10" = {
    model <- svd_rcppml(A_sparse, 10, tol = 1e-5, maxit = 1000)
  },
  "irlba Rank 10" = {
    model <- irlba::irlba(A_sparse, 10, tol = 1e-5, maxit = 1000)
  }
  # "RcppML Rank 50" = {
  #   model <- svd_rcppml(A_sparse, 50, tol = 1e-5, maxit = 1000)
  # },
  # "irlba Rank 50" = {
  #   model <- irlba::irlba(A_sparse, 50, tol = 1e-5, maxit = 1000)
  # },
  # 
  # "RcppML Rank 100" = {
  #   model <- svd_rcppml(A_sparse, 100, tol = 1e-5, maxit = 1000)
  # },
  # "irlba Rank 100" = {
  #   model <- irlba::irlba(A_sparse, 100, tol = 1e-5, maxit = 1000)
  # }
)
mbm
```
