# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_nnls <- function(a, b, fast_maxit = 10L, cd_maxit = 100L, cd_tol = 1e-8, nonneg = TRUE) {
    .Call('_RcppML_Rcpp_nnls', PACKAGE = 'RcppML', a, b, fast_maxit, cd_maxit, cd_tol, nonneg)
}

Rcpp_cdnnls <- function(a, b, x, cd_maxit = 100L, cd_tol = 1e-8, nonneg = TRUE) {
    .Call('_RcppML_Rcpp_cdnnls', PACKAGE = 'RcppML', a, b, x, cd_maxit, cd_tol, nonneg)
}

Rcpp_mse_sparse <- function(A_S4, w, d, h, threads) {
    .Call('_RcppML_Rcpp_mse_sparse', PACKAGE = 'RcppML', A_S4, w, d, h, threads)
}

Rcpp_mse_dense <- function(A, w, d, h, threads) {
    .Call('_RcppML_Rcpp_mse_dense', PACKAGE = 'RcppML', A, w, d, h, threads)
}

Rcpp_project_sparse <- function(A_S4, w, nonneg, fast_maxit, cd_maxit, cd_tol, L1, threads) {
    .Call('_RcppML_Rcpp_project_sparse', PACKAGE = 'RcppML', A_S4, w, nonneg, fast_maxit, cd_maxit, cd_tol, L1, threads)
}

Rcpp_project_dense <- function(A, w, nonneg, fast_maxit, cd_maxit, cd_tol, L1, threads) {
    .Call('_RcppML_Rcpp_project_dense', PACKAGE = 'RcppML', A, w, nonneg, fast_maxit, cd_maxit, cd_tol, L1, threads)
}

Rcpp_nmf_sparse <- function(A_S4, At_S4, symmetric, w_init, tol = 1e-3, nonneg = TRUE, L1_w = 0, L1_h = 0, maxit = 100L, diag = TRUE, fast_maxit = 10L, cd_maxit = 100L, cd_tol = 1e-8, verbose = FALSE, threads = 0L) {
    .Call('_RcppML_Rcpp_nmf_sparse', PACKAGE = 'RcppML', A_S4, At_S4, symmetric, w_init, tol, nonneg, L1_w, L1_h, maxit, diag, fast_maxit, cd_maxit, cd_tol, verbose, threads)
}

Rcpp_nmf_dense <- function(A, symmetric, w_init, tol = 1e-3, nonneg = TRUE, L1_w = 0, L1_h = 0, maxit = 100L, diag = TRUE, fast_maxit = 10L, cd_maxit = 100L, cd_tol = 1e-8, verbose = FALSE, threads = 0L) {
    .Call('_RcppML_Rcpp_nmf_dense', PACKAGE = 'RcppML', A, symmetric, w_init, tol, nonneg, L1_w, L1_h, maxit, diag, fast_maxit, cd_maxit, cd_tol, verbose, threads)
}

Rcpp_nmf1_sparse <- function(A_S4, w_init, tol, nonneg, maxit, verbose, diag) {
    .Call('_RcppML_Rcpp_nmf1_sparse', PACKAGE = 'RcppML', A_S4, w_init, tol, nonneg, maxit, verbose, diag)
}

Rcpp_nmf1_dense <- function(A, w_init, tol, nonneg, maxit, verbose, diag) {
    .Call('_RcppML_Rcpp_nmf1_dense', PACKAGE = 'RcppML', A, w_init, tol, nonneg, maxit, verbose, diag)
}

Rcpp_nmf2_sparse <- function(A_S4, w_init, tol, nonneg, maxit, verbose, diag, samples) {
    .Call('_RcppML_Rcpp_nmf2_sparse', PACKAGE = 'RcppML', A_S4, w_init, tol, nonneg, maxit, verbose, diag, samples)
}

Rcpp_nmf2_dense <- function(A, w_init, tol, nonneg, maxit, verbose, diag, samples) {
    .Call('_RcppML_Rcpp_nmf2_dense', PACKAGE = 'RcppML', A, w_init, tol, nonneg, maxit, verbose, diag, samples)
}

Rcpp_bipartition_sparse <- function(A_S4, w, samples, tol = 1e-4, nonneg = TRUE, calc_centers = TRUE, calc_dist = TRUE, maxit = 100L, verbose = FALSE, diag = TRUE, seed = 0L) {
    .Call('_RcppML_Rcpp_bipartition_sparse', PACKAGE = 'RcppML', A_S4, w, samples, tol, nonneg, calc_centers, calc_dist, maxit, verbose, diag, seed)
}

Rcpp_bipartition_dense <- function(A, w, samples, tol = 1e-4, nonneg = TRUE, calc_centers = TRUE, calc_dist = TRUE, maxit = 100L, verbose = FALSE, diag = TRUE) {
    .Call('_RcppML_Rcpp_bipartition_dense', PACKAGE = 'RcppML', A, w, samples, tol, nonneg, calc_centers, calc_dist, maxit, verbose, diag)
}

Rcpp_dclust_sparse <- function(A_S4, w, min_dist, min_samples, verbose, threads, bipartition_tol, bipartition_nonneg, bipartition_maxit, calc_centers, diag) {
    .Call('_RcppML_Rcpp_dclust_sparse', PACKAGE = 'RcppML', A_S4, w, min_dist, min_samples, verbose, threads, bipartition_tol, bipartition_nonneg, bipartition_maxit, calc_centers, diag)
}

Rcpp_dclust_dense <- function(A, w, min_dist, min_samples, verbose, threads, bipartition_tol, bipartition_nonneg, bipartition_maxit, calc_centers, diag, seed) {
    .Call('_RcppML_Rcpp_dclust_dense', PACKAGE = 'RcppML', A, w, min_dist, min_samples, verbose, threads, bipartition_tol, bipartition_nonneg, bipartition_maxit, calc_centers, diag, seed)
}

