# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_nnls <- function(a, b, fast_maxit, cd_maxit, cd_tol, nonneg, L1) {
    .Call('_RcppML_Rcpp_nnls', PACKAGE = 'RcppML', a, b, fast_maxit, cd_maxit, cd_tol, nonneg, L1)
}

Rcpp_project_sparse <- function(A_S4, w, nonneg, L1, cd_maxit, fast_maxit, cd_tol, threads) {
    .Call('_RcppML_Rcpp_project_sparse', PACKAGE = 'RcppML', A_S4, w, nonneg, L1, cd_maxit, fast_maxit, cd_tol, threads)
}

Rcpp_project_dense <- function(A, w, nonneg, L1, cd_maxit, fast_maxit, cd_tol, threads) {
    .Call('_RcppML_Rcpp_project_dense', PACKAGE = 'RcppML', A, w, nonneg, L1, cd_maxit, fast_maxit, cd_tol, threads)
}

Rcpp_projectInPlace_sparse <- function(A_S4, h, nonneg, L1, cd_maxit, fast_maxit, cd_tol, threads) {
    .Call('_RcppML_Rcpp_projectInPlace_sparse', PACKAGE = 'RcppML', A_S4, h, nonneg, L1, cd_maxit, fast_maxit, cd_tol, threads)
}

Rcpp_projectInPlace_dense <- function(A, h, nonneg, L1, cd_maxit, fast_maxit, cd_tol, threads) {
    .Call('_RcppML_Rcpp_projectInPlace_dense', PACKAGE = 'RcppML', A, h, nonneg, L1, cd_maxit, fast_maxit, cd_tol, threads)
}

Rcpp_nmf_sparse <- function(A_S4, k, seed, tol, nonneg, L1, maxit, updateInPlace, diag, verbose, cd_maxit, fast_maxit, cd_tol, threads) {
    .Call('_RcppML_Rcpp_nmf_sparse', PACKAGE = 'RcppML', A_S4, k, seed, tol, nonneg, L1, maxit, updateInPlace, diag, verbose, cd_maxit, fast_maxit, cd_tol, threads)
}

Rcpp_nmf_dense <- function(A, k, seed, tol, nonneg, L1, maxit, updateInPlace, diag, verbose, cd_maxit, fast_maxit, cd_tol, threads) {
    .Call('_RcppML_Rcpp_nmf_dense', PACKAGE = 'RcppML', A, k, seed, tol, nonneg, L1, maxit, updateInPlace, diag, verbose, cd_maxit, fast_maxit, cd_tol, threads)
}

Rcpp_mse_sparse <- function(A_S4, w, d, h, threads) {
    .Call('_RcppML_Rcpp_mse_sparse', PACKAGE = 'RcppML', A_S4, w, d, h, threads)
}

Rcpp_mse_dense <- function(A, w, d, h, threads) {
    .Call('_RcppML_Rcpp_mse_dense', PACKAGE = 'RcppML', A, w, d, h, threads)
}

Rcpp_bipartition_sparse <- function(A_S4, samples, tol, nonneg, calc_dist, maxit, verbose, seed) {
    .Call('_RcppML_Rcpp_bipartition_sparse', PACKAGE = 'RcppML', A_S4, samples, tol, nonneg, calc_dist, maxit, verbose, seed)
}

Rcpp_bipartition_dense <- function(A, samples, tol, nonneg, calc_dist, maxit, verbose, seed) {
    .Call('_RcppML_Rcpp_bipartition_dense', PACKAGE = 'RcppML', A, samples, tol, nonneg, calc_dist, maxit, verbose, seed)
}

Rcpp_dclust_sparse <- function(A_S4, min_dist, min_samples, verbose, threads, tol, nonneg, maxit, seed) {
    .Call('_RcppML_Rcpp_dclust_sparse', PACKAGE = 'RcppML', A_S4, min_dist, min_samples, verbose, threads, tol, nonneg, maxit, seed)
}

